### ISSUE TITLE
Find out from @tomspilman what files on disk indicate the existence of NDA'd SDKs

### ISSUE THREAD

**Issue by hach-que** [Protobuild/Protobuild#135]
We need some way in the Protobuild package system to know that the user is authorized to download NDA'd platform code.

My rough plan is:

* For each NDA'd platform, find either a private key in the SDK, or pick a random file in the SDK that we can generate a private key from consistently.
* Use that private key to sign the request to the package server.
* The package server verifies the request against the public key.
* If it passes, the package server returns the URL to the NDA'd package.

This prevents anyone from forging their ownership of an SDK, because they must actually have the SDK installed in order to download a package (or have obtained the SDK in the past so they have a private key).

To find out how to do the first step, I need to know what SDK files exist on disk for each platform.  Only then can I write code that can generate a private key from them.  @tomspilman will know what files exist on disk for various SDKs.

**Comment by tomspilman** [comment]
> We need some way in the Protobuild package system to know that the user is authorized to download NDA'd platform code.

This seems to come up a lot between us.  I want a feature that works with files that already exist on the users machine.  You want to automate the git commands.  Same old dance.

I'm willing to help you with figuring out how to make this work for your Protogame stuff, but understand now MonoGame will not use of this feature out of the box.  We 100% expect developers to do their own git work or copy of zipped files or whatever to put the files in the right place.

> My rough plan is:

What specifically do you mean by the "SDK"?  Do you mean like the "MonoGame SDK for PS4"?

**Comment by hach-que** [comment]
As previously discussed, Protobuild packages do not prevent you from doing things manually.  They do not have any special features that "put files in a directory" doesn't grant you.

They are just a way of automating the tedious setup and configuration that would normally be present with copying library or project files somewhere.

For example, you can't do `git submodule add` in the public MonoGame repository to reference the PS4 repository (even if the PS4 repository is private), because Git treats that as a failure to clone.  You *can* however do this with the proposal above, because it treats it as "you don't have access to this platform".  The alternative to this is asking the user to fork the public repo, and do `git submodule add` (to maintain it as a subfolder), or adding the subfolder to `.gitignore` manually so that it won't cause a stale state in Git.

> What specifically do you mean by the "SDK"? Do you mean like the "MonoGame SDK for PS4"?

I mean the actual PS4 development SDK that would reside on a developer's machine.

**Comment by tomspilman** [comment]
> I mean the actual PS4 development SDK 

Yeah... none of that is shareable in any way or form.  It is 100% private.

**Comment by hach-que** [comment]
Yeah, we don't need to share any of it, we just need to know the existence of the files on disk.

**Comment by hach-que** [comment]
I've applied for the PS4 program so that I can actually support this kind of scenario better.  I'll update here based on the outcome of that.
