### ISSUE TITLE
Win10 SDK version detection missing trailing .0

### ISSUE THREAD

**Issue by tomspilman** [Protobuild/Protobuild#169]
The Win10 SDK version detection done here:

https://github.com/Protobuild/Protobuild/blob/master/Protobuild.Internal/BuildResources/GenerationFunctions.cs#L513

Doesn't seem to work with the current VS2015 release.

I am getting `10.0.14366` (a new preview version of the Win10 SDK) as the version which is incorrect... it should have an extra trailing zero:  `10.0.14366.0`.

Without the trailing zero VS2015 detects it as a missing version of the SDK and prompts you to install it... taking you to a broken URL as that version doesn't exist.

I don't know if for all versions we just need a trailing `.0` or if we are missing some information in the SDK detection.

**Comment by hach-que** [comment]
I'll quickly test to see if that's the case for existing versions, or just new versions.

**Comment by hach-que** [comment]
Okay, seems like I don't have any SDKs installed on this machine.

Can you screenshot what the registry key looks like for you?

**Comment by hach-que** [comment]
As a quick workaround for this issue while I prepare an actual fix, if you do `--extract-xslt` it'll give you `GenerationFunctions.cs` in your `Build\` directory, which you can then patch to add the `.0`.

I'll have to wait until I'm on a broadband connection before I can install the SDKs to find out what's going on - I'm currently on mobile data.

**Comment by tomspilman** [comment]
> Can you screenshot what the registry key looks like for you?

Unfortunately i'm away from my Win10 machine...  i'll see what I can do in the morning.  I know when I looked in the registry the `v10.0` folder wasn't there which was weird as it was correctly detecting things.  Am I missing something?

> As a quick workaround for this issue while I prepare an actual fix,

Yeah i'm aware of the workarounds. :)

**Comment by hach-que** [comment]
So for reference, this is what the registry looks like when installing the current SDK:

![image](https://cloud.githubusercontent.com/assets/504826/16255963/c8bf8c48-3891-11e6-99df-d74e5dd3a834.png)

I'll install the preview SDK now and see what changes.

**Comment by hach-que** [comment]
Yup, looks like they changed it to drop the 0, though I'm confused why Visual Studio would require it if they're actually dropping it from the version number:

![image](https://cloud.githubusercontent.com/assets/504826/16256382/2a0f41ca-3895-11e6-904e-51fda926bbe8.png)

**Comment by tomspilman** [comment]
It is probably safe to assume if there is not 4 values to the version number that you should append `.0`s to the end to pad it out.

**Comment by hach-que** [comment]
This should be fixed in 0b21b85.  With the preview SDK, I now get version numbers with 4 components:

![image](https://cloud.githubusercontent.com/assets/504826/16289829/dad7c2ec-393b-11e6-901f-56ef4ad798f4.png)

Let me know if you're still having issues
