### ISSUE TITLE
Build Configuration Request

### ISSUE THREAD

**Issue by wheresthecode** [Protobuild/Protobuild#206]
I'd like to propose allowing multiple build configurations . There are many Android app stores and each one might need custom files, and preprocessor definitions.  I would like to be able to create configurations like Android_Demo_PlayStore, Android_PlayStore, Android_AmazonUnderground, etc.

Each build configuration could also be a separate platform that derives from a built in platform. For example the manifest file could declare a new platform called Anrdoid_PlatStore that inherits from the Android platform.

**Comment by hach-que** [comment]
The recommended way of doing something like this is through [Service Dependencies](http://protobuild.readthedocs.io/en/latest/service_dependencies.html).

Then you can run `Protobuild.exe --generate Android --enable MyApp/PlayStore` and have files or references included as appropriate.

**Comment by wheresthecode** [comment]
Fantastic. Thanks for the quick response. Also, your work on Protobuild is much appreciated! It's made bringing my windows phone game to Android and iOS much easier!
