### ISSUE TITLE
Android projects are generated with Novell targets instead of Xamarin targets on Linux

### ISSUE THREAD

**Issue by cra0zy** [Protobuild/Protobuild#208]
Android projects generated from Linux are generated with Novell targets file instead of the new Xamarin one. I noticed that you had a check in <a href="https://github.com/Protobuild/Protobuild/blob/35a15c0a1755e15bc4109fffa6c812fd834b7c85/Protobuild.Internal/BuildResources/GenerateProject.CSharp.xslt#L2108">GenerateProject.CSharp.xslt</a> which you could just return true if Protobuild is running on Linux, since Novell targets never existed for it.

**Comment by hach-que** [comment]
Oh I didn't realised Xamarin supported Linux desktops for Android development.  Feel free to submit a PR to make the change if you need it urgently; I'm very busy at the moment so I won't get a chance to dev + test this kind of change.

**Comment by cra0zy** [comment]
> Oh I didn't realised Xamarin supported Linux desktops for Android development.

They don't, but you can install it from source code (it's a bit convoluted). I did manage to compile MonoGame from source once I changed the .targets file.

> Feel free to submit a PR to make the change if you need it urgently

Do you have some predefined way to check OS from xslt files?

**Comment by cra0zy** [comment]
Side note, I'll probably make xamarin-android .run installer for Linux once I get some free time (like I did for MonoDevelop: https://github.com/cra0zy/monodevelop-run-installer)

**Comment by hach-que** [comment]
Not really; there's a bunch of functions inside GenerationFunctions.cs, which are available to the XSLT.  I'd probably just test to see if the Xamarin targets file exists on whatever Linux path it resides at, and if that exists, just use that (instead of testing for a specific platform).

**Comment by cra0zy** [comment]
I can't seem to get `Protobuild.exe --automated-build` to work, it crashes with: https://gist.github.com/cra0zy/6ddc40ea1f5d3f6c3f33f202063019d8

Anyway the needed changes are: https://github.com/cra0zy/Protobuild/commit/f2437a4fdf03448858a07296ccc3f1390f9e2fc0

**Comment by hach-que** [comment]
I've seen that occasionally, usually it's a corrupt Git repository. Can you
delete the cached repo on disk and try again?

**Comment by cra0zy** [comment]
Yup, that fixed it, #214
