### ISSUE TITLE
Support .NET Standard 1.4, 1.5, 1.6 and future 2.0

### ISSUE THREAD

**Issue by amerkoleci** [Protobuild/Protobuild#219]
Don't know if there is any issues about this, would be nice to have support for .NET standard project generation.

Thanks

**Comment by hach-que** [comment]
You can already do this with `FrameworkVersions`: http://protobuild.readthedocs.io/en/latest/project_properties.html#frameworkversions

The recommended usage of PCLs are bait-and-switch, so you should do `--generate PCL` with a customized framework version if you want to target it.
