### ISSUE TITLE
Is it possible to 'inherit' project definitions?

### ISSUE THREAD

**Issue by raizam** [Protobuild/Protobuild#259]
Hey @hach-que ,

I'm using Monogame sources as a git submodule, and I would like to reuse `MonoGame.Framework.definition` externaly. The behavior I'm looking for is to inherit every references and have the sourcefiles linking the original path location. I also would like to exclude some files from the original definition.
What would be the best strategy to achieve this?

**Comment by hach-que** [comment]
There's nothing in the way to support this - Did you want your solution to have your own copy of MonoGame.Framework instead of the one in Git? Or did you want both?

**Comment by raizam** [comment]
The idea was to have my own modified Monogame without touching the original git repository.
I'd like to override files as needed, from the top folder.

Anyway, I think I'm going to giving up

**Comment by hach-que** [comment]
Yeah, we don't support that. Our recommended way of handling that is to fork the MonoGame repository, and set up some kind of build CI job that automatically rebases or merges new versions of MonoGame in. That's how we have the RedpointGames fork configured.

I'm going to close this issue as this feature isn't something we're going to pursue.
