### ISSUE TITLE
Are there plains to dismiss support in the next future?

### ISSUE THREAD

**Issue by Eversor** [Protobuild/Protobuild#260]
I'm starting a two+ years Monogame project and i'd love to support it with protobuild, do you have any plans to drop support in the near future?

**Comment by hach-que** [comment]
There's no plans to drop support in the future.

Protobuild is also a reasonably stable project and has gone through a lot of real-world testing with it's usage in the MonoGame project directly, so even though there isn't a high frequency of commits or high number of recent commits, this shouldn't be taken as a lack of support; rather that the project is at a maturity level where there's not a pressing demand to make changes or throw lots of new features in.

**Comment by Eversor** [comment]
Sure, i would have asked elsewhere but the support page redirects here 👍
