### ISSUE TITLE
Discussion: Cross-packaging of Protobuild packages to NuGet packages

### ISSUE THREAD

**Issue by hach-que** [Protobuild/Protobuild#91]
Currently a lot of people consume NuGet packages in their projects.  While NuGet paradigm doesn't adapt well to cross-platform projects, users still expect NuGet packages to be provided and developers usually still provide them.

Because of Protobuild's design, it semantically knows how a project is put together and structures binary packages appropriately.  We can cross-package a Protobuild package into a NuGet package with only a few extra bits of information (in particular, the additional NuGet package details which in Protobuild are only stored in the index).

This should reduce the amount of maintenance required in managing and creating packages.  Most critically it removes the need for creating NuGet specification files (.nuspec) for projects, because we can generate it automatically.

I've implemented an experimental version of Protobuild that provides this function via a `--cross-pack` command: https://github.com/hach-que/Protobuild/commit/2bee4228e20f935e151d189b9ade8d932dbd2cfa.

I'd like to know if this functionality is useful for people, and what's missing from the current implementation.

**Comment by Daniel15** [comment]
> While NuGet paradigm doesn't adapt well to cross-platform projects

Why wouldn't it? A NuGet package is just a package containing files. Assemblies can be framework-specific.

**Comment by hach-que** [comment]
Frameworks are not the same as platforms.  This is particularly evident when you are performing native calls in libraries such as MonoGame; it is not efficient in MonoGame to switch between DirectX and OpenGL at runtime based on the OS, even though framework-wise the framework is always .NET 4.0 across all platforms.

**Comment by hach-que** [comment]
This is now superseded by #177.
